// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean IncreaseConeAngle
        {
            get
            {
                return SteamVR_Actions.default_IncreaseConeAngle;
            }
        }
        
        public virtual SteamVR_Action_Boolean DecreaseConeAngle
        {
            get
            {
                return SteamVR_Actions.default_DecreaseConeAngle;
            }
        }
        
        public virtual SteamVR_Action_Boolean IncreaseConeHeight
        {
            get
            {
                return SteamVR_Actions.default_IncreaseConeHeight;
            }
        }
        
        public virtual SteamVR_Action_Boolean DecreaseConeHeight
        {
            get
            {
                return SteamVR_Actions.default_DecreaseConeHeight;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
